export let meals = [
  "Almoço",
  "Brunch",
  "Café da manhã",
  "Jantar",
  "Lanche",
  "Sobremesa",
];

export let categories = [
  "Acompanhamentos",
  "Aperitivos",
  "Aves",
  "Bolos e Tortas",
  "Carnes",
  "Doces",
  "Entradas",
  "Frutos do Mar",
  "Massas",
  "Molhos",
  "Peixes",
  "Pratos Principais",
  "Saladas",
  "Sopas e Caldos",
  "Vegano",
  "Vegetariano",
];

export let countries = [
  "Alemã",
  "Argentina",
  "Australiana",
  "Belga",
  "Brasileira",
  "Chilena",
  "Chinesa",
  "Colombiana",
  "Coreana",
  "Cubana",
  "Espanhola",
  "Estadunidense",
  "Francesa",
  "Grega",
  "Holandesa",
  "Húngara",
  "Inglesa",
  "Irlandesa",
  "Israelita",
  "Italiana",
  "Japonesa",
  "Libanesa",
  "Marroquina",
  "Mexicana",
  "Norueguesa",
  "Peruana",
  "Polonesa",
  "Portuguesa",
  "Russa",
  "Suíça",
  "Tailandesa",
  "Turca",
  "Uruguaia",
  "Vietnamita",
];

export let ingredients = [
  "Bebidas",
  "Biscoitos",
  "Carnes",
  "Conservas",
  "Doces e Chocolates",
  "Farinhas",
  "Frios e Embutidos",
  "Frutas",
  "Grãos",
  "Laticínios",
  "Legumes e Verduras",
  "Leveduras",
  "Massas",
  "Molhos e Condimentos",
  "Nozes e Sementes",
  "Ovos",
  "Pães",
  "Óleos",
];

export let country = [
  { value: "África do Sul", countryName: "África do Sul" },
  { value: "Albânia", countryName: "Albânia" },
  { value: "Alemanha", countryName: "Alemanha" },
  { value: "Andorra", countryName: "Andorra" },
  { value: "Angola", countryName: "Angola" },
  { value: "Anguilla", countryName: "Anguilla" },
  { value: "Antigua", countryName: "Antigua" },
  { value: "Arábia Saudita", countryName: "Arábia Saudita" },
  { value: "Argentina", countryName: "Argentina" },
  { value: "Armênia", countryName: "Armênia" },
  { value: "Aruba", countryName: "Aruba" },
  { value: "Austrália", countryName: "Austrália" },
  { value: "Áustria", countryName: "Áustria" },
  { value: "Azerbaijão", countryName: "Azerbaijão" },
  { value: "Bahamas", countryName: "Bahamas" },
  { value: "Bahrein", countryName: "Bahrein" },
  { value: "Bangladesh", countryName: "Bangladesh" },
  { value: "Barbados", countryName: "Barbados" },
  { value: "Bélgica", countryName: "Bélgica" },
  { value: "Benin", countryName: "Benin" },
  { value: "Bermudas", countryName: "Bermudas" },
  { value: "Botsuana", countryName: "Botsuana" },
  { value: "Brasil", countryName: "Brasil" },
  { value: "Brunei", countryName: "Brunei" },
  { value: "Bulgária", countryName: "Bulgária" },
  { value: "Burkina Fasso", countryName: "Burkina Fasso" },
  { value: "botão", countryName: "botão" },
  { value: "Cabo Verde", countryName: "Cabo Verde" },
  { value: "Camarões", countryName: "Camarões" },
  { value: "Camboja", countryName: "Camboja" },
  { value: "Canadá", countryName: "Canadá" },
  { value: "Cazaquistão", countryName: "Cazaquistão" },
  { value: "Chade", countryName: "Chade" },
  { value: "Chile", countryName: "Chile" },
  { value: "China", countryName: "China" },
  { value: "Cidade do Vaticano", countryName: "Cidade do Vaticano" },
  { value: "Colômbia", countryName: "Colômbia" },
  { value: "Congo", countryName: "Congo" },
  { value: "Coréia do Sul", countryName: "Coréia do Sul" },
  { value: "Costa do Marfim", countryName: "Costa do Marfim" },
  { value: "Costa Rica", countryName: "Costa Rica" },
  { value: "Croácia", countryName: "Croácia" },
  { value: "Dinamarca", countryName: "Dinamarca" },
  { value: "Djibuti", countryName: "Djibuti" },
  { value: "Dominica", countryName: "Dominica" },
  { value: "EUA", countryName: "EUA" },
  { value: "Egito", countryName: "Egito" },
  { value: "El Salvador", countryName: "El Salvador" },
  { value: "Emirados Árabes", countryName: "Emirados Árabes" },
  { value: "Equador", countryName: "Equador" },
  { value: "Eritréia", countryName: "Eritréia" },
  { value: "Escócia", countryName: "Escócia" },
  { value: "Eslováquia", countryName: "Eslováquia" },
  { value: "Eslovênia", countryName: "Eslovênia" },
  { value: "Espanha", countryName: "Espanha" },
  { value: "Estônia", countryName: "Estônia" },
  { value: "Etiópia", countryName: "Etiópia" },
  { value: "Fiji", countryName: "Fiji" },
  { value: "Filipinas", countryName: "Filipinas" },
  { value: "Finlândia", countryName: "Finlândia" },
  { value: "França", countryName: "França" },
  { value: "Gabão", countryName: "Gabão" },
  { value: "Gâmbia", countryName: "Gâmbia" },
  { value: "Gana", countryName: "Gana" },
  { value: "Geórgia", countryName: "Geórgia" },
  { value: "Gibraltar", countryName: "Gibraltar" },
  { value: "Granada", countryName: "Granada" },
  { value: "Grécia", countryName: "Grécia" },
  { value: "Guadalupe", countryName: "Guadalupe" },
  { value: "Guam", countryName: "Guam" },
  { value: "Guatemala", countryName: "Guatemala" },
  { value: "Guiana", countryName: "Guiana" },
  { value: "Guiana Francesa", countryName: "Guiana Francesa" },
  { value: "Guiné-bissau", countryName: "Guiné-bissau" },
  { value: "Haiti", countryName: "Haiti" },
  { value: "Holanda", countryName: "Holanda" },
  { value: "Honduras", countryName: "Honduras" },
  { value: "Hong Kong", countryName: "Hong Kong" },
  { value: "Hungria", countryName: "Hungria" },
  { value: "Iêmen", countryName: "Iêmen" },
  { value: "Ilhas Cayman", countryName: "Ilhas Cayman" },
  { value: "Ilhas Cook", countryName: "Ilhas Cook" },
  { value: "Ilhas Curaçao", countryName: "Ilhas Curaçao" },
  { value: "Ilhas Marshall", countryName: "Ilhas Marshall" },
  { value: "Ilhas Turks & Caicos", countryName: "Ilhas Turks & Caicos" },
  { value: "Ilhas Virgens (brit.)", countryName: "Ilhas Virgens (brit.)" },
  { value: "Ilhas Virgens(amer.)", countryName: "Ilhas Virgens(amer.)" },
  { value: "Ilhas Wallis e Futuna", countryName: "Ilhas Wallis e Futuna" },
  { value: "Índia", countryName: "Índia" },
  { value: "Indonésia", countryName: "Indonésia" },
  { value: "Inglaterra", countryName: "Inglaterra" },
  { value: "Irlanda", countryName: "Irlanda" },
  { value: "Islândia", countryName: "Islândia" },
  { value: "Israel", countryName: "Israel" },
  { value: "Itália", countryName: "Itália" },
  { value: "Jamaica", countryName: "Jamaica" },
  { value: "Japão", countryName: "Japão" },
  { value: "Jordânia", countryName: "Jordânia" },
  { value: "Kuwait", countryName: "Kuwait" },
  { value: "Latvia", countryName: "Latvia" },
  { value: "Líbano", countryName: "Líbano" },
  { value: "Liechtenstein", countryName: "Liechtenstein" },
  { value: "Lituânia", countryName: "Lituânia" },
  { value: "Luxemburgo", countryName: "Luxemburgo" },
  { value: "Macau", countryName: "Macau" },
  { value: "Macedônia", countryName: "Macedônia" },
  { value: "Madagascar", countryName: "Madagascar" },
  { value: "Malásia", countryName: "Malásia" },
  { value: "Malaui", countryName: "Malaui" },
  { value: "Mali", countryName: "Mali" },
  { value: "Malta", countryName: "Malta" },
  { value: "Marrocos", countryName: "Marrocos" },
  { value: "Martinica", countryName: "Martinica" },
  { value: "Mauritânia", countryName: "Mauritânia" },
  { value: "Mauritius", countryName: "Mauritius" },
  { value: "México", countryName: "México" },
  { value: "Moldova", countryName: "Moldova" },
  { value: "Mônaco", countryName: "Mônaco" },
  { value: "Montserrat", countryName: "Montserrat" },
  { value: "Nepal", countryName: "Nepal" },
  { value: "Nicarágua", countryName: "Nicarágua" },
  { value: "Niger", countryName: "Niger" },
  { value: "Nigéria", countryName: "Nigéria" },
  { value: "Noruega", countryName: "Noruega" },
  { value: "Nova Caledônia", countryName: "Nova Caledônia" },
  { value: "Nova Zelândia", countryName: "Nova Zelândia" },
  { value: "Omã", countryName: "Omã" },
  { value: "Palau", countryName: "Palau" },
  { value: "Panamá", countryName: "Panamá" },
  { value: "Papua-nova Guiné", countryName: "Papua-nova Guiné" },
  { value: "Paquistão", countryName: "Paquistão" },
  { value: "Peru", countryName: "Peru" },
  { value: "Polinésia Francesa", countryName: "Polinésia Francesa" },
  { value: "Polônia", countryName: "Polônia" },
  { value: "Porto Rico", countryName: "Porto Rico" },
  { value: "Portugal", countryName: "Portugal" },
  { value: "Qatar", countryName: "Qatar" },
  { value: "Quênia", countryName: "Quênia" },
  { value: "Rep. Dominicana", countryName: "Rep. Dominicana" },
  { value: "Rep. Tcheca", countryName: "Rep. Tcheca" },
  { value: "Reunion", countryName: "Reunion" },
  { value: "Romênia", countryName: "Romênia" },
  { value: "Ruanda", countryName: "Ruanda" },
  { value: "Rússia", countryName: "Rússia" },
  { value: "Saipan", countryName: "Saipan" },
  { value: "Samoa Americana", countryName: "Samoa Americana" },
  { value: "Senegal", countryName: "Senegal" },
  { value: "Serra Leone", countryName: "Serra Leone" },
  { value: "Seychelles", countryName: "Seychelles" },
  { value: "Singapura", countryName: "Singapura" },
  { value: "Síria", countryName: "Síria" },
  { value: "Sri Lanka", countryName: "Sri Lanka" },
  { value: "St. Kitts & Nevis", countryName: "St. Kitts & Nevis" },
  { value: "St. Lúcia", countryName: "St. Lúcia" },
  { value: "St. Vincent", countryName: "St. Vincent" },
  { value: "Sudão", countryName: "Sudão" },
  { value: "Suécia", countryName: "Suécia" },
  { value: "Suiça", countryName: "Suiça" },
  { value: "Suriname", countryName: "Suriname" },
  { value: "Tailândia", countryName: "Tailândia" },
  { value: "Taiwan", countryName: "Taiwan" },
  { value: "Tanzânia", countryName: "Tanzânia" },
  { value: "Togo", countryName: "Togo" },
  { value: "Trinidad & Tobago", countryName: "Trinidad & Tobago" },
  { value: "Tunísia", countryName: "Tunísia" },
  { value: "Turquia", countryName: "Turquia" },
  { value: "Ucrânia", countryName: "Ucrânia" },
  { value: "Uganda", countryName: "Uganda" },
  { value: "Uruguai", countryName: "Uruguai" },
  { value: "Venezuela", countryName: "Venezuela" },
  { value: "Vietnã", countryName: "Vietnã" },
  { value: "Zaire", countryName: "Zaire" },
  { value: "Zâmbia", countryName: "Zâmbia" },
  { value: "Zimbábue", countryName: "Zimbábue" },
];
