export let meals = [
  "Almoço",
  "Brunch",
  "Café da manhã",
  "Jantar",
  "Lanche",
  "Sobremesa",
];

export let homeMeals = [
  "Todas",
  "Almoço",
  "Brunch",
  "Café da manhã",
  "Jantar",
  "Lanche",
  "Sobremesa",
];

export let categories = [
  "Acompanhamentos",
  "Aperitivos",
  "Aves",
  "Bolos e Tortas",
  "Carnes",
  "Doces",
  "Entradas",
  "Frutos do Mar",
  "Massas",
  "Molhos",
  "Peixes",
  "Pratos Principais",
  "Saladas",
  "Sopas e Caldos",
  "Vegano",
  "Vegetariano",
];

export let countries = [
  "Alemã",
  "Argentina",
  "Australiana",
  "Belga",
  "Brasileira",
  "Chilena",
  "Chinesa",
  "Colombiana",
  "Coreana",
  "Cubana",
  "Espanhola",
  "Estadunidense",
  "Francesa",
  "Grega",
  "Holandesa",
  "Húngara",
  "Inglesa",
  "Irlandesa",
  "Israelita",
  "Italiana",
  "Japonesa",
  "Libanesa",
  "Marroquina",
  "Mexicana",
  "Norueguesa",
  "Peruana",
  "Polonesa",
  "Portuguesa",
  "Russa",
  "Suíça",
  "Tailandesa",
  "Turca",
  "Uruguaia",
  "Vietnamita",
];

export let ingredients = [
  "Arroz Arbóreo",
  "Arroz Basmati",
  "Arroz Branco",
  "Arroz Integral",
  "Arroz Negro",
  "Arroz Parboilizado",
  "Arroz Vermelho",
  "Aveia",
  "Café",
  "Cevada",
  "Gergelim",
  "Grão de Bico",
  "Lentilha",
  "Milho para Pipoca",
  "Quinoa",
  "Soja",
  "Trigo",
  "Amendoim",
  "Avelã",
  "Castanha do Pará",
  "Chia",
  "Linhaça",
  "Macadâmia",
  "Noz",
  "Pinhão",
  "Pistache",
  "Abacate",
  "Abacaxi",
  "Ameixa",
  "Amora",
  "Açaí",
  "Banana",
  "Banana da Terra",
  "Cajú",
  "Cana de Açúcar",
  "Caqui",
  "Cereja",
  "Cupuaçu",
  "Coco",
  "Damasco",
  "Figo",
  "Framboesa",
  "Goiaba",
  "Groselha",
  "Jabuticaba",
  "Kiwi",
  "Laranja",
  "Lima",
  "Limão",
  "Limão Siciliano",
  "Mamão",
  "Manga",
  "Maracujá",
  "Maçã ",
  "Melancia",
  "Melão",
  "Mirtilo",
  "Morango",
  "Pequi",
  "Pêra",
  "Pêssego",
  "Romã",
  "Tamarindo",
  "Tangerina",
  "Uva",
  "Uvas Passas",
  "Pão Brioche",
  "Pão Francês",
  "Pão Integral",
  "Pão de Forma",
  "Torrada",
  "Abobrinha",
  "Abóbora",
  "Acelga",
  "Aipo",
  "Alecrim",
  "Alface",
  "Alho",
  "Alho Poró",
  "Aspargo",
  "Batata",
  "Beterraba",
  "Brocólis",
  "Cará",
  "Cebola",
  "Cebola Roxa",
  "Cebolinha",
  "Cenoura",
  "Chuchu",
  "Coentro",
  "Cogumelo Funghi",
  "Cogumelo Shitake",
  "Cominho",
  "Couve",
  "Couve Flor",
  "Ervilha",
  "Espinafre",
  "Feijão Branco",
  "Feijão Carioca",
  "Feijão Fradinho",
  "Feijão Preto",
  "Feijão de Corda",
  "Gengibre",
  "Inhame",
  "Jiló",
  "Mandioca",
  "Manjericão",
  "Maxixe",
  "Nabo",
  "Pepino",
  "Picles",
  "Pimentão Amarelo",
  "Pimentão Verde",
  "Pimentão Vermelho",
  "Rabanete",
  "Repolho",
  "Repolho Roxo",
  "Salsa",
  "Tomate",
  "Tomate Cereja",
  "Tomilho",
  "Vagem",
  "Cogumelo",
  "Milho Verde",
  "Palmito",
  "Tomate Seco",
  "Amido de Milho",
  "Farinha de Aveia",
  "Farinha de Banana",
  "Farinha de Centeio",
  "Farinha de Linhaça",
  "Farinha de Mandioca",
  "Farinha de Milho",
  "Farinha de Quinoa",
  "Farinha de Rosca",
  "Farinha de Soja",
  "Farinha de Tapioca",
  "Farinha de Trigo",
  "Farinha de Trigo Integral",
  "Flocos de Milho",
  "Fubá",
  "Tapioca",
  "Argolinha",
  "Bavette",
  "Bucatini",
  "Cabelo de Anjo",
  "Caracol",
  "Conchiglione",
  "Conchinha",
  "Espaguete",
  "Fettuccine",
  "Fusili",
  "Gnocchi",
  "Gravata",
  "Macarrão Instantâneo",
  "Ninho",
  "Pappardelle",
  "Penne",
  "Ravioli",
  "Rigatoni",
  "Tagliatelle",
  "Tortiglioni",
  "Achocolatado",
  "Água de Coco",
  "Aguardente",
  "Cerveja",
  "Champanhe",
  "Cidra",
  "Conhaque",
  "Gin",
  "Licor",
  "Rum",
  "Sakê",
  "Tequila",
  "Vinho Tinto",
  "Vinho Branco",
  "Vinho Rosé",
  "Vodka",
  "Whiskey",
  "Leite Integral",
  "Vinho do Porto",
  "Leite Desnatado",
  "Leite Sem Lactose",
  "Leite de Soja",
  "Leite de Amêndoa",
  "Leite Fermentado",
  "Leite de Cabra",
  "Bebida Láctea",
  "Catupiry",
  "Coalhada",
  "Cream Cheese",
  "Creme de Leite",
  "Iogurte",
  "Leite Condensado",
  "Leite de Coco",
  "Manteiga",
  "Queijo Azul",
  "Queijo Brie",
  "Queijo Cheddar",
  "Queijo Coalho",
  "Queijo Cottage",
  "Queijo Emental",
  "Queijo Gorgonzola",
  "Queijo Gouda",
  "Queijo Grana Padano",
  "Queijo Gruyère",
  "Queijo Manchego",
  "Queijo Muçarela",
  "Queijo Parmesão",
  "Queijo Prato",
  "Queijo Provolone",
  "Queijo Roquefort",
  "Queijo Serra da Canastra",
  "Queijo Suíço",
  "Queijo de Minas",
  "Requeijão",
  "Ricota",
  "Tofu",
  "Clara de Ovo de Galinha",
  "Gema de Ovo de Galinha",
  "Ovo de Codorna",
  "Ovo de Galinha",
  "Ovo de Pata",
  "Azeite",
  "Azeite Trufado",
  "Azeite de Dendê",
  "Banha",
  "Creme Vegetal",
  "Margarina",
  "Óleo Vegetal",
  "Óleo de Amendoim",
  "Óleo de Cártamo",
  "Óleo de Gergelim",
  "Óleo de Milho",
  "Óleo de Soja",
  "Apresuntado",
  "Calabresa",
  "Lombo",
  "Mortadela",
  "Peito de Peru",
  "Presunto",
  "Presunto Parma",
  "Salame",
  "Salsicha",
  "Salsichão",
  "Tempero em Tablete",
  "Erva Doce",
  "Hortelã",
  "Ketchup",
  "Maionese",
  "Mostarda",
  "Orégano",
  "Pimenta Calabresa",
  "Pimenta Malagueta",
  "Pimenta de Cheiro",
  "Pimenta do Reino",
  "Sal",
  "Sal Grosso",
  "Sal com Alho",
  "Vinagre",
  "Biscoito Champanhe",
  "Biscoito Maisena",
  "Biscoito de Polvilho",
  "Adoçante Líquido",
  "Adoçante em Pó",
  "Açúcar",
  "Cacau em Pó",
  "Caramelo",
  "Cereja em Calda",
  "Chantilly",
  "Chocolate Amargo",
  "Chocolate Branco",
  "Chocolate Meio Amargo",
  "Chocolate ao Leite",
  "Creme de Avelã",
  "Doce de Leite",
  "Essência de Baunilha",
  "Frutas Cristalizadas",
  "Geléia de Amora",
  "Geléia de Framboesa",
  "Geléia de Frutas Vermelhas",
  "Geléia de Morango",
  "Geléia de Uva",
  "Goiabada",
  "Mel",
  "Pêssego em Calda",
  "Suspiro",
  "Acém",
  "Alcatra",
  "Asa de Frango",
  "Atum",
  "Bacon",
  "Camarão",
  "Carne Bovina",
  "Carne Suína",
  "Carne de Frango",
  "Carne Moída",
  "Carne de Sol",
  "Charque",
  "Contra Filé",
  "Cordeiro",
  "Costela Bovina",
  "Costela Suína",
  "Coxa de Frango",
  "Coxão Duro",
  "Coxão Mole",
  "Filé Mignon ",
  "Filé Mignon Suíno",
  "Filé de Avestruz",
  "Fraldinha",
  "Lagarto",
  "Lagosta",
  "Lagostim",
  "Linguiça Suína",
  "Linguiça de Frango",
  "Lula",
  "Língua Bovina",
  "Peito de Pato",
  "Mexilhão",
  "Mocotó",
  "Ostra",
  "Panceta",
  "Pato",
  "Peito de Frango",
  "Peixe",
  "Peru",
  "Picanha",
  "Pintado",
  "Polvo",
  "Robalo",
  "Salmão",
  "Sardinha",
  "Sobrecoxa de Frango",
  "T-Bone",
  "Tilápia",
  "Tucunaré",
  "Fermento Biológico Fresco",
  "Fermento Biológico Seco",
  "Fermento Biológico Seco Instantâneo",
  "Fermento Químico em Pó",
];

export let country = [
  { value: "África do Sul", countryName: "África do Sul" },
  { value: "Albânia", countryName: "Albânia" },
  { value: "Alemanha", countryName: "Alemanha" },
  { value: "Andorra", countryName: "Andorra" },
  { value: "Angola", countryName: "Angola" },
  { value: "Anguilla", countryName: "Anguilla" },
  { value: "Antigua", countryName: "Antigua" },
  { value: "Arábia Saudita", countryName: "Arábia Saudita" },
  { value: "Argentina", countryName: "Argentina" },
  { value: "Armênia", countryName: "Armênia" },
  { value: "Aruba", countryName: "Aruba" },
  { value: "Austrália", countryName: "Austrália" },
  { value: "Áustria", countryName: "Áustria" },
  { value: "Azerbaijão", countryName: "Azerbaijão" },
  { value: "Bahamas", countryName: "Bahamas" },
  { value: "Bahrein", countryName: "Bahrein" },
  { value: "Bangladesh", countryName: "Bangladesh" },
  { value: "Barbados", countryName: "Barbados" },
  { value: "Bélgica", countryName: "Bélgica" },
  { value: "Benin", countryName: "Benin" },
  { value: "Bermudas", countryName: "Bermudas" },
  { value: "Botsuana", countryName: "Botsuana" },
  { value: "Brasil", countryName: "Brasil" },
  { value: "Brunei", countryName: "Brunei" },
  { value: "Bulgária", countryName: "Bulgária" },
  { value: "Burkina Fasso", countryName: "Burkina Fasso" },
  { value: "botão", countryName: "botão" },
  { value: "Cabo Verde", countryName: "Cabo Verde" },
  { value: "Camarões", countryName: "Camarões" },
  { value: "Camboja", countryName: "Camboja" },
  { value: "Canadá", countryName: "Canadá" },
  { value: "Cazaquistão", countryName: "Cazaquistão" },
  { value: "Chade", countryName: "Chade" },
  { value: "Chile", countryName: "Chile" },
  { value: "China", countryName: "China" },
  { value: "Cidade do Vaticano", countryName: "Cidade do Vaticano" },
  { value: "Colômbia", countryName: "Colômbia" },
  { value: "Congo", countryName: "Congo" },
  { value: "Coréia do Sul", countryName: "Coréia do Sul" },
  { value: "Costa do Marfim", countryName: "Costa do Marfim" },
  { value: "Costa Rica", countryName: "Costa Rica" },
  { value: "Croácia", countryName: "Croácia" },
  { value: "Dinamarca", countryName: "Dinamarca" },
  { value: "Djibuti", countryName: "Djibuti" },
  { value: "Dominica", countryName: "Dominica" },
  { value: "EUA", countryName: "EUA" },
  { value: "Egito", countryName: "Egito" },
  { value: "El Salvador", countryName: "El Salvador" },
  { value: "Emirados Árabes", countryName: "Emirados Árabes" },
  { value: "Equador", countryName: "Equador" },
  { value: "Eritréia", countryName: "Eritréia" },
  { value: "Escócia", countryName: "Escócia" },
  { value: "Eslováquia", countryName: "Eslováquia" },
  { value: "Eslovênia", countryName: "Eslovênia" },
  { value: "Espanha", countryName: "Espanha" },
  { value: "Estônia", countryName: "Estônia" },
  { value: "Etiópia", countryName: "Etiópia" },
  { value: "Fiji", countryName: "Fiji" },
  { value: "Filipinas", countryName: "Filipinas" },
  { value: "Finlândia", countryName: "Finlândia" },
  { value: "França", countryName: "França" },
  { value: "Gabão", countryName: "Gabão" },
  { value: "Gâmbia", countryName: "Gâmbia" },
  { value: "Gana", countryName: "Gana" },
  { value: "Geórgia", countryName: "Geórgia" },
  { value: "Gibraltar", countryName: "Gibraltar" },
  { value: "Granada", countryName: "Granada" },
  { value: "Grécia", countryName: "Grécia" },
  { value: "Guadalupe", countryName: "Guadalupe" },
  { value: "Guam", countryName: "Guam" },
  { value: "Guatemala", countryName: "Guatemala" },
  { value: "Guiana", countryName: "Guiana" },
  { value: "Guiana Francesa", countryName: "Guiana Francesa" },
  { value: "Guiné-bissau", countryName: "Guiné-bissau" },
  { value: "Haiti", countryName: "Haiti" },
  { value: "Holanda", countryName: "Holanda" },
  { value: "Honduras", countryName: "Honduras" },
  { value: "Hong Kong", countryName: "Hong Kong" },
  { value: "Hungria", countryName: "Hungria" },
  { value: "Iêmen", countryName: "Iêmen" },
  { value: "Ilhas Cayman", countryName: "Ilhas Cayman" },
  { value: "Ilhas Cook", countryName: "Ilhas Cook" },
  { value: "Ilhas Curaçao", countryName: "Ilhas Curaçao" },
  { value: "Ilhas Marshall", countryName: "Ilhas Marshall" },
  { value: "Ilhas Turks & Caicos", countryName: "Ilhas Turks & Caicos" },
  { value: "Ilhas Virgens (brit.)", countryName: "Ilhas Virgens (brit.)" },
  { value: "Ilhas Virgens(amer.)", countryName: "Ilhas Virgens(amer.)" },
  { value: "Ilhas Wallis e Futuna", countryName: "Ilhas Wallis e Futuna" },
  { value: "Índia", countryName: "Índia" },
  { value: "Indonésia", countryName: "Indonésia" },
  { value: "Inglaterra", countryName: "Inglaterra" },
  { value: "Irlanda", countryName: "Irlanda" },
  { value: "Islândia", countryName: "Islândia" },
  { value: "Israel", countryName: "Israel" },
  { value: "Itália", countryName: "Itália" },
  { value: "Jamaica", countryName: "Jamaica" },
  { value: "Japão", countryName: "Japão" },
  { value: "Jordânia", countryName: "Jordânia" },
  { value: "Kuwait", countryName: "Kuwait" },
  { value: "Latvia", countryName: "Latvia" },
  { value: "Líbano", countryName: "Líbano" },
  { value: "Liechtenstein", countryName: "Liechtenstein" },
  { value: "Lituânia", countryName: "Lituânia" },
  { value: "Luxemburgo", countryName: "Luxemburgo" },
  { value: "Macau", countryName: "Macau" },
  { value: "Macedônia", countryName: "Macedônia" },
  { value: "Madagascar", countryName: "Madagascar" },
  { value: "Malásia", countryName: "Malásia" },
  { value: "Malaui", countryName: "Malaui" },
  { value: "Mali", countryName: "Mali" },
  { value: "Malta", countryName: "Malta" },
  { value: "Marrocos", countryName: "Marrocos" },
  { value: "Martinica", countryName: "Martinica" },
  { value: "Mauritânia", countryName: "Mauritânia" },
  { value: "Mauritius", countryName: "Mauritius" },
  { value: "México", countryName: "México" },
  { value: "Moldova", countryName: "Moldova" },
  { value: "Mônaco", countryName: "Mônaco" },
  { value: "Montserrat", countryName: "Montserrat" },
  { value: "Nepal", countryName: "Nepal" },
  { value: "Nicarágua", countryName: "Nicarágua" },
  { value: "Niger", countryName: "Niger" },
  { value: "Nigéria", countryName: "Nigéria" },
  { value: "Noruega", countryName: "Noruega" },
  { value: "Nova Caledônia", countryName: "Nova Caledônia" },
  { value: "Nova Zelândia", countryName: "Nova Zelândia" },
  { value: "Omã", countryName: "Omã" },
  { value: "Palau", countryName: "Palau" },
  { value: "Panamá", countryName: "Panamá" },
  { value: "Papua-nova Guiné", countryName: "Papua-nova Guiné" },
  { value: "Paquistão", countryName: "Paquistão" },
  { value: "Peru", countryName: "Peru" },
  { value: "Polinésia Francesa", countryName: "Polinésia Francesa" },
  { value: "Polônia", countryName: "Polônia" },
  { value: "Porto Rico", countryName: "Porto Rico" },
  { value: "Portugal", countryName: "Portugal" },
  { value: "Qatar", countryName: "Qatar" },
  { value: "Quênia", countryName: "Quênia" },
  { value: "Rep. Dominicana", countryName: "Rep. Dominicana" },
  { value: "Rep. Tcheca", countryName: "Rep. Tcheca" },
  { value: "Reunion", countryName: "Reunion" },
  { value: "Romênia", countryName: "Romênia" },
  { value: "Ruanda", countryName: "Ruanda" },
  { value: "Rússia", countryName: "Rússia" },
  { value: "Saipan", countryName: "Saipan" },
  { value: "Samoa Americana", countryName: "Samoa Americana" },
  { value: "Senegal", countryName: "Senegal" },
  { value: "Serra Leone", countryName: "Serra Leone" },
  { value: "Seychelles", countryName: "Seychelles" },
  { value: "Singapura", countryName: "Singapura" },
  { value: "Síria", countryName: "Síria" },
  { value: "Sri Lanka", countryName: "Sri Lanka" },
  { value: "St. Kitts & Nevis", countryName: "St. Kitts & Nevis" },
  { value: "St. Lúcia", countryName: "St. Lúcia" },
  { value: "St. Vincent", countryName: "St. Vincent" },
  { value: "Sudão", countryName: "Sudão" },
  { value: "Suécia", countryName: "Suécia" },
  { value: "Suiça", countryName: "Suiça" },
  { value: "Suriname", countryName: "Suriname" },
  { value: "Tailândia", countryName: "Tailândia" },
  { value: "Taiwan", countryName: "Taiwan" },
  { value: "Tanzânia", countryName: "Tanzânia" },
  { value: "Togo", countryName: "Togo" },
  { value: "Trinidad & Tobago", countryName: "Trinidad & Tobago" },
  { value: "Tunísia", countryName: "Tunísia" },
  { value: "Turquia", countryName: "Turquia" },
  { value: "Ucrânia", countryName: "Ucrânia" },
  { value: "Uganda", countryName: "Uganda" },
  { value: "Uruguai", countryName: "Uruguai" },
  { value: "Venezuela", countryName: "Venezuela" },
  { value: "Vietnã", countryName: "Vietnã" },
  { value: "Zaire", countryName: "Zaire" },
  { value: "Zâmbia", countryName: "Zâmbia" },
  { value: "Zimbábue", countryName: "Zimbábue" },
];
